# Directory pattern
scope:web:
  - changed-files:
      - any-glob-to-any-file: "apps/web/**"

scope:docs:
  - changed-files:
      - any-glob-to-any-file: "apps/docs/**"

scope:shared:
  - changed-files:
      - any-glob-to-any-file: ["packages/**", "*"]

scope:ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

# Branch pattern
enhancement:
  - head-branch: ["^feature/"]

bug:
  - head-branch: ["^bugfix/", "^hotfix/"]

release:
  - head-branch: ["^release/"]
  - base-branch: ["master"]
