name: "Pull Request Labeler"

on:
  pull_request:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Label
        uses: actions/labeler@v5
