name: Create PR to Sync Development with Hotfix/Bugfix Branches

on:
  pull_request:
    branches:
      - main
      - release/*
    types: [closed]

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  dump_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  create_pr_from_main:
    if: >-
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'hotfix/') &&
      github.base_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      pull-requests: "write"
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PR to sync development with main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --base development --head "${GITHUB_BASE_REF}" --title "Sync development with main" --body "PR created by GithubActions"
